import type { ThemeDefinition, ThemeTokens } from './types';

function tokensFromXaml(t: Omit<ThemeTokens, never>): ThemeTokens {
  return t;
}

const corporateTokens = tokensFromXaml({
  sidebar: '#0c2340',
  sidebarMid: '#163b5c',
  sidebarActive: '#1e4a6e',
  accent: '#006b9e',
  accentHover: '#005a85',
  teal: '#00857a',
  contentBackground: '#eef1f4',
  card: '#ffffff',
  border: '#d5dce4',
  textPrimary: '#1a2b3c',
  textSecondary: '#5a6b7d',
  textOnDark: '#e8eef4',
  textOnDarkMuted: '#9bb0c4',
  accentLight: '#e8f4fa',
  panelMuted: '#f6f8fa',
  success: '#0d7a55',
  warning: '#b8860b',
  danger: '#b42318',
  dangerLight: '#fdecec',
  dangerBorder: '#f5c4c4',
  gold: '#c5a572',
  shadow: '#0c2340',
  textOnLight: '#1a2b3c',
  headerBar: '#ffffff',
});

const midnightTokens = tokensFromXaml({
  sidebar: '#1e1b4b',
  sidebarMid: '#312e81',
  sidebarActive: '#4338ca',
  accent: '#6366f1',
  accentHover: '#4f46e5',
  teal: '#14b8a6',
  contentBackground: '#f5f3ff',
  card: '#ffffff',
  border: '#e0e7ff',
  textPrimary: '#1e1b4b',
  textSecondary: '#64748b',
  textOnDark: '#e0e7ff',
  textOnDarkMuted: '#a5b4fc',
  accentLight: '#eef2ff',
  panelMuted: '#f8fafc',
  success: '#059669',
  warning: '#d97706',
  danger: '#dc2626',
  dangerLight: '#fee2e2',
  dangerBorder: '#fecaca',
  gold: '#f59e0b',
  shadow: '#312e81',
  textOnLight: '#1e1b4b',
  headerBar: '#ffffff',
});

const emeraldTokens = tokensFromXaml({
  sidebar: '#14532d',
  sidebarMid: '#166534',
  sidebarActive: '#15803d',
  accent: '#10b981',
  accentHover: '#059669',
  teal: '#0d9488',
  contentBackground: '#f0fdf4',
  card: '#ffffff',
  border: '#bbf7d0',
  textPrimary: '#14532d',
  textSecondary: '#4b5563',
  textOnDark: '#dcfce7',
  textOnDarkMuted: '#86efac',
  accentLight: '#ecfdf5',
  panelMuted: '#f9fafb',
  success: '#047857',
  warning: '#ca8a04',
  danger: '#dc2626',
  dangerLight: '#fee2e2',
  dangerBorder: '#fecaca',
  gold: '#a16207',
  shadow: '#14532d',
  textOnLight: '#14532d',
  headerBar: '#ffffff',
});

const blueWhiteTokens = tokensFromXaml({
  sidebar: '#0a0a0a',
  sidebarMid: '#171717',
  sidebarActive: '#262626',
  accent: '#2563eb',
  accentHover: '#1d4ed8',
  teal: '#0ea5e9',
  contentBackground: '#ffffff',
  card: '#ffffff',
  border: '#e5e7eb',
  textPrimary: '#111827',
  textSecondary: '#6b7280',
  textOnDark: '#ffffff',
  textOnDarkMuted: '#9ca3af',
  accentLight: '#eff6ff',
  panelMuted: '#f9fafb',
  success: '#16a34a',
  warning: '#ca8a04',
  danger: '#dc2626',
  dangerLight: '#fee2e2',
  dangerBorder: '#fecaca',
  gold: '#78716c',
  shadow: '#111827',
  textOnLight: '#111827',
  headerBar: '#ffffff',
});

/** Ported from IMS/Services/ThemeService.cs + Resources/Themes/*.xaml */
export const ALL_THEMES: ThemeDefinition[] = [
  {
    id: 'Corporate',
    displayName: 'Corporate Navy',
    badgeText: 'CORPORATE',
    description: 'Classic navy sidebar with professional blue accents.',
    palette: {
      primary: '#006b9e',
      secondary: '#0c2340',
      teal: '#00857a',
      slate: '#5a6b7d',
      success: '#0d7a55',
      warning: '#b8860b',
      danger: '#b42318',
      purple: '#5b4b8a',
      gold: '#9a7b4f',
    },
    tokens: corporateTokens,
  },
  {
    id: 'MidnightIndigo',
    displayName: 'Midnight Indigo',
    badgeText: 'MIDNIGHT INDIGO',
    description: 'Deep violet navigation with indigo highlights and cool lavender surfaces.',
    palette: {
      primary: '#6366f1',
      secondary: '#1e1b4b',
      teal: '#14b8a6',
      slate: '#64748b',
      success: '#059669',
      warning: '#d97706',
      danger: '#dc2626',
      purple: '#a855f7',
      gold: '#f59e0b',
    },
    tokens: midnightTokens,
  },
  {
    id: 'EmeraldForest',
    displayName: 'Emerald Forest',
    badgeText: 'EMERALD FOREST',
    description: 'Forest-green sidebar with emerald accents and mint-tinted content areas.',
    palette: {
      primary: '#10b981',
      secondary: '#14532d',
      teal: '#0d9488',
      slate: '#6b7280',
      success: '#047857',
      warning: '#ca8a04',
      danger: '#dc2626',
      purple: '#7c3aed',
      gold: '#a16207',
    },
    tokens: emeraldTokens,
  },
  {
    id: 'BlueWhiteBlack',
    displayName: 'Blue, White & Black',
    badgeText: 'BLUE WHITE',
    description: 'Black navigation bar, clean white workspaces, and bold blue accents throughout.',
    palette: {
      primary: '#2563eb',
      secondary: '#111827',
      teal: '#0ea5e9',
      slate: '#6b7280',
      success: '#16a34a',
      warning: '#ca8a04',
      danger: '#dc2626',
      purple: '#4f46e5',
      gold: '#78716c',
    },
    tokens: blueWhiteTokens,
  },
];

export const DEFAULT_THEME_ID = 'Corporate' as const;

export function getThemeById(id: string | null | undefined): ThemeDefinition {
  return ALL_THEMES.find((t) => t.id === id) ?? ALL_THEMES[0];
}
