// <auto-generated />
using System;
using Ims.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ims.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ImsDbContext))]
    [Migration("20260716102732_NumberedDocuments")]
    partial class NumberedDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ims.Domain.Config.FinancialYear", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinancialYearName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousYearId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseName")
                        .IsUnique();

                    b.HasIndex("FinancialYearName")
                        .IsUnique();

                    b.ToTable("financial_years", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Config.SoftwareLicense", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extensions_json");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlanDays")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExtensionDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("software_licenses", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Entities.Counter", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "Key")
                        .IsUnique();

                    b.ToTable("counters", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Entities.DeliveryChallanDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<int>("DocNo")
                        .HasColumnType("integer");

                    b.Property<string>("DocPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("doc_prefix");

                    b.Property<string>("FormattedDocNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_doc_no");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<string>("SalesMan")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tran_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "FormattedDocNo")
                        .IsUnique();

                    b.HasIndex("YearDatabaseName", "DocPrefix", "DocNo")
                        .IsUnique();

                    b.ToTable("delivery_challans", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Entities.GrnDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<int>("DocNo")
                        .HasColumnType("integer");

                    b.Property<string>("DocPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("doc_prefix");

                    b.Property<string>("FormattedDocNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_doc_no");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<string>("SalesMan")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tran_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "FormattedDocNo")
                        .IsUnique();

                    b.HasIndex("YearDatabaseName", "DocPrefix", "DocNo")
                        .IsUnique();

                    b.ToTable("grns", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Entities.PurchaseInvoiceDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<int>("DocNo")
                        .HasColumnType("integer");

                    b.Property<string>("DocPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("doc_prefix");

                    b.Property<string>("FormattedDocNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_doc_no");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<string>("SalesMan")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tran_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "FormattedDocNo")
                        .IsUnique();

                    b.HasIndex("YearDatabaseName", "DocPrefix", "DocNo")
                        .IsUnique();

                    b.ToTable("purchase_invoices", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Entities.PurchaseOrderDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<int>("DocNo")
                        .HasColumnType("integer");

                    b.Property<string>("DocPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("doc_prefix");

                    b.Property<string>("FormattedDocNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_doc_no");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<string>("SalesMan")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tran_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "FormattedDocNo")
                        .IsUnique();

                    b.HasIndex("YearDatabaseName", "DocPrefix", "DocNo")
                        .IsUnique();

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Entities.PurchaseReturnDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<int>("DocNo")
                        .HasColumnType("integer");

                    b.Property<string>("DocPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("doc_prefix");

                    b.Property<string>("FormattedDocNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_doc_no");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<string>("SalesMan")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tran_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "FormattedDocNo")
                        .IsUnique();

                    b.HasIndex("YearDatabaseName", "DocPrefix", "DocNo")
                        .IsUnique();

                    b.ToTable("purchase_returns", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Entities.SalesInvoiceDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<int>("DocNo")
                        .HasColumnType("integer");

                    b.Property<string>("DocPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("doc_prefix");

                    b.Property<string>("FormattedDocNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_doc_no");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<string>("SalesMan")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tran_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "FormattedDocNo")
                        .IsUnique();

                    b.HasIndex("YearDatabaseName", "DocPrefix", "DocNo")
                        .IsUnique();

                    b.ToTable("sales_invoices", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Entities.SalesReturnDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<int>("DocNo")
                        .HasColumnType("integer");

                    b.Property<string>("DocPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("doc_prefix");

                    b.Property<string>("FormattedDocNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_doc_no");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<string>("SalesMan")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tran_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "FormattedDocNo")
                        .IsUnique();

                    b.HasIndex("YearDatabaseName", "DocPrefix", "DocNo")
                        .IsUnique();

                    b.ToTable("sales_returns", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Masters.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("CustomerType")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Gstin")
                        .HasColumnType("text");

                    b.Property<string>("MobileNo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("OpeningBalanceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pan")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "Code")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Masters.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanPrintBarcodeLabels")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "Username")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Masters.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Gstin")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoImage")
                        .HasColumnType("text");

                    b.Property<string>("LogoText")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfSupply")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "Code")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Ims.Domain.Masters.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("AssemblyType")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("GstExempt")
                        .HasColumnType("boolean");

                    b.Property<string>("HsnCode")
                        .HasColumnType("text");

                    b.Property<decimal>("Igst")
                        .HasColumnType("numeric");

                    b.Property<string>("Length")
                        .HasColumnType("text");

                    b.Property<decimal>("MinOrderQty")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductImage")
                        .HasColumnType("text");

                    b.Property<string>("ProductMainGroup")
                        .HasColumnType("text");

                    b.Property<string>("ProductSubGroup")
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("PurchaseUom")
                        .HasColumnType("text");

                    b.Property<decimal>("ReorderQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("SaleUom")
                        .HasColumnType("text");

                    b.Property<bool>("SerialApplicable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<decimal>("StockQty")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxPercent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearDatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("year_database_name");

                    b.HasKey("Id");

                    b.HasIndex("YearDatabaseName", "Code")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
